language: ruby
sudo: false
rvm:
  - 2.3.3
branches:
  only:
    - master

script: bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database pwb_dummy_test;' -U postgres
env:
  - SECRET_KEY_BASE="$(bundle exec rake secret)"
services:
  - postgresql
addons:
  postgresql: "9.4"