# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly..


development:
  secret_key_base: # Paste output of $ rake secret here 
  # sendgrid_username: 
  # sendgrid_password: 
  # cloudinary_url: 
  # facebook_app_id: 
  # facebook_app_secret: 

test:
  secret_key_base: # Paste output of $ rake secret here 

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  cloudinary_url: <%= ENV['CLOUDINARY_URL'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>


precompile:
  secret_key_base: # Paste output of $ rake secret here 
